#!/bin/bash -x
# @ production environment, remove -x option
# Basic Bash Script Deployment
# (c) Jan 2022 allowebs.com generated by masteringunixshell.net

# if you want to see your debug messages, uncomment this variable
#DEBUG_IS_ON=yes

# you can use this function for debug messages
# usage: command: "debug File Is Open" --(gives oputput)--> "At 11:44:00 File Is Open"
function debug()
{
  if [ "${DEBUG_IS_ON}" = "yes" ]
  then
    NOW=$(date +"%T")
    echo "At $NOW Debug: ${*}" >&2
  fi
}


function print_help()
{
  echo -e "Syntax: $0 [-1] [-2] [-3] [-4] [-5] [-6] [-7] >&2"
  echo -e "\t[-1]: Update System"
  echo -e "\t[-2]: Install Homebrew"
  echo -e "\t[-3]: Install Froxlor"
  echo -e "\t[-4]: Install YunoHost"
  echo -e "\t[-5]: Install DigitalOcean Monitor"
  echo -e "\t[-6]: Change Time zone System"
  echo -e "\t[-7]: Clean System"
  exit 1
}

# Update System
function process_Update()
{
     debug Procesing 'Update'
  sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
}

# Install Homebrew
function process_Homebrew()
{
   debug Procesing 'Homebrew'
   sudo useradd -m -p all0webs.cOm non-root
su non-root
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
su root
}

# Install Froxlor
function process_Froxlor()
{
   debug Procesing 'Froxlor'
   apt-get -y install apt-transport-https lsb-release ca-certificates gnupg
wget -O - https://deb.froxlor.org/froxlor.gpg | apt-key add -
echo "deb https://deb.froxlor.org/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/froxlor.list
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt autoremove -y
sudo apt-get clean -y
sudo apt-get autoremove --purge -y
apt-get install froxlor
}

# Install YunoHost
function process_YunoHost()
{
   debug Procesing 'YunoHost'
}

# Install DigitalOcean Monitor
function process_DigitalOcean Monitor()
{
  debug Procesing 'DigitalOcean Monitor'
  sudo curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash
}

# Change Time zone System
function process_Change Time zone()
{
  debug Procesing 'Change Time zone'
  dpkg-reconfigure tzdata 
}

# Clean System
function process_Clean()
{
   debug Procesing 'Clean'
   sudo apt autoremove -y
sudo apt-get clean -y
sudo apt-get autoremove --purge -y
}

while getopts ":1234567" o
do
  case "$o" in
  1) process_Update ;;
  2) process_Homebrew ;;
  3) process_Froxlor ;;
  4) process_YunoHost ;;
  5) process_DigitalOcean Monitor ;;
  6) process_Change Time zone ;;
  7) process_Clean ;;
  *)
  esac
done;
